# 01 Numpy. Пшенин Владислав Игоревич 6133

In [1]:
import numpy as np

## I. Взять из документации по numpy 12 любых функций / методов / операторов и продемонстрировать из работу в блокноте

**1) Creating array**

In [7]:
a = np.arange(15).reshape(5, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

**2) Some information about array**

In [9]:
a.ndim, a.shape, a.dtype

(2, (5, 3), dtype('int32'))

**3) Creating array (diff way)**

In [11]:
a = np.ones( (4,4,8), dtype=np.int16 )
a

array([[[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]]], dtype=int16)

In [23]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**4) Arithmetic operators (Exponentiation)**

In [24]:
b = b**2
b

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

**5) Arithmetic operators (Relational)**

In [25]:
b<20

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

**6) Arithmetic operators (Multiplication)**

In [26]:
b*b

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561],
      dtype=int32)

**7) Arithmetic operators (Sin)**

In [28]:
10*np.sin(b)

array([ 0.        ,  8.41470985, -7.56802495,  4.12118485, -2.87903317,
       -1.3235175 , -9.91778853, -9.53752653,  9.20026038, -6.29887994])

**8) Creating array (random)**

In [30]:
a = np.random.random((2,3))
a

array([[0.75413466, 0.18769748, 0.87950403],
       [0.22371645, 0.36033643, 0.57764833]])

**9) Sum, min, max**

In [35]:
a.sum(),a.min(),a.max()

(2.98303738327656, 0.18769747504281087, 0.8795040335842005)

**10) Array sorting**

In [34]:
np.sort(a)

array([[0.18769748, 0.75413466, 0.87950403],
       [0.22371645, 0.36033643, 0.57764833]])

**11) Mean, median, std**

In [36]:
a.mean(), np.median(a), np.std(a)

(0.49717289721276003, 0.4689923791330427, 0.26075545003494865)

**12) Concatenate arrays**

In [40]:
np.concatenate((a,a), axis=1)

array([[0.75413466, 0.18769748, 0.87950403, 0.75413466, 0.18769748,
        0.87950403],
       [0.22371645, 0.36033643, 0.57764833, 0.22371645, 0.36033643,
        0.57764833]])

## II. Сгенерировать OLAP-куб, где фиксируем продажи товаров в розничной сети по магазинам

**OLAP-куб**

Оси:
* 0: ID группы товаров (100)
* 1: ID магазина (10)
* 2: день месяца, в котором осуществляются продажи (31)

In [173]:
olap = np.zeros((100,10,31))

In [174]:
for i in range (olap.shape[0]):
    a = np.random.randint(1,101)
    for j in range (olap.shape[1]):
        b = a + a * np.random.rand()
        for k in range (olap.shape[2]):
            olap[i][j][k] = b * np.random.randint(1,10)

## III. Для получившегося OLAP-куба посчитать суммарные, средние, минимальные и максимальные продажи (на самом деле любые агрегатные функции можно использовать), зафиксировав значения по одной, двум или трём осям

**Срез для 0-товара по всем дням и магазинам**

In [175]:
olap[0,:,:]

array([[ 98.08223581, 294.24670742,  65.3881572 , 163.47039301,
        163.47039301, 163.47039301, 261.55262882, 294.24670742,
        130.77631441, 261.55262882,  65.3881572 , 196.16447161,
        196.16447161,  32.6940786 , 228.85855022,  98.08223581,
         32.6940786 , 261.55262882,  98.08223581, 196.16447161,
        228.85855022, 294.24670742,  98.08223581,  65.3881572 ,
        130.77631441, 130.77631441,  32.6940786 ,  98.08223581,
        228.85855022, 261.55262882, 196.16447161],
       [ 96.45984404,  96.45984404, 289.37953212, 289.37953212,
        128.61312539,  64.30656269,  32.15328135, 225.07296943,
         64.30656269,  96.45984404,  64.30656269,  96.45984404,
        257.22625077, 160.76640673, 128.61312539, 289.37953212,
        225.07296943,  96.45984404, 128.61312539,  32.15328135,
         32.15328135, 128.61312539,  64.30656269, 160.76640673,
        160.76640673, 128.61312539,  32.15328135, 192.91968808,
        225.07296943, 225.07296943,  64.30656269],
       [459.51581078, 114.8789527 , 344.63685809, 229.75790539,
        287.19738174, 344.63685809, 402.07633444, 172.31842904,
        344.63685809, 402.07633444, 172.31842904, 287.19738174,
        459.51581078, 344.63685809, 459.51581078,  57.43947635,
        229.75790539, 229.75790539, 402.07633444, 516.95528713,
        229.75790539, 114.8789527 , 172.31842904,  57.43947635,
        402.07633444,  57.43947635, 459.51581078, 229.75790539,
        114.8789527 , 516.95528713, 402.07633444],
       [390.47726217, 446.25972819, 167.34739807, 278.91233012,
        390.47726217, 390.47726217, 167.34739807, 502.04219422,
        390.47726217, 111.56493205, 278.91233012, 278.91233012,
        334.69479615, 334.69479615, 111.56493205, 167.34739807,
        334.69479615, 502.04219422, 278.91233012, 111.56493205,
        223.1298641 , 502.04219422, 111.56493205, 223.1298641 ,
        390.47726217,  55.78246602, 167.34739807, 390.47726217,
        390.47726217, 167.34739807, 278.91233012],
       [261.34675769, 348.46234358,  87.1155859 , 392.02013653,
        261.34675769, 130.67337884, 217.78896474,  43.55779295,
        348.46234358,  87.1155859 ,  43.55779295, 304.90455064,
        304.90455064,  43.55779295, 174.23117179,  43.55779295,
        130.67337884,  43.55779295, 392.02013653, 217.78896474,
        304.90455064, 130.67337884, 304.90455064, 217.78896474,
        217.78896474, 304.90455064, 174.23117179, 304.90455064,
        348.46234358, 217.78896474, 304.90455064],
       [ 87.29352626, 174.58705253, 305.52734193, 218.23381566,
         87.29352626, 261.88057879, 130.9402894 ,  87.29352626,
        392.82086819, 349.17410506, 130.9402894 , 174.58705253,
        261.88057879,  43.64676313, 349.17410506, 218.23381566,
        349.17410506,  43.64676313,  87.29352626, 174.58705253,
        130.9402894 , 261.88057879, 305.52734193,  87.29352626,
        130.9402894 , 218.23381566,  87.29352626,  43.64676313,
        392.82086819, 130.9402894 , 218.23381566],
       [427.17017852, 237.31676584, 332.24347218, 284.78011901,
        189.85341267,  47.46335317,  47.46335317,  47.46335317,
         94.92670634, 379.70682535, 237.31676584, 379.70682535,
         94.92670634, 379.70682535, 332.24347218,  47.46335317,
        379.70682535,  47.46335317, 379.70682535, 284.78011901,
        284.78011901, 332.24347218, 427.17017852, 332.24347218,
        284.78011901,  94.92670634, 284.78011901, 237.31676584,
        237.31676584,  94.92670634, 284.78011901],
       [329.28123314, 423.36158546, 235.20088081,  47.04017616,
        188.16070465,  47.04017616, 423.36158546, 282.24105697,
         94.08035232,  94.08035232, 235.20088081, 282.24105697,
        423.36158546, 376.3214093 , 329.28123314, 141.12052849,
         47.04017616,  47.04017616,  94.08035232, 282.24105697,
        282.24105697, 423.36158546, 235.20088081, 282.24105697,
        141.12052849, 376.3214093 , 282.24105697, 423.36158546,
        329.28123314, 188.16070465,  47.04017616],
       [108.23197243, 288.61859315, 144.30929658, 216.46394486,
        144.30929658,  36.07732414,  36.07732414, 324.6959173 ,
        108.23197243,  36.07732414, 144.30929658, 144.30929658,
        252.54126901, 252.54126901,  72.15464829,  72.15464829,
        324.6959173 , 144.30929658, 288.61859315, 108.23197243,
         36.07732414, 216.46394486, 180.38662072, 216.46394486,
         72.15464829, 216.46394486,  72.15464829, 144.30929658,
         36.07732414,  36.07732414, 108.23197243],
       [344.64618585, 393.88135525, 393.88135525, 196.94067763,
        147.70550822, 443.11652466, 196.94067763, 344.64618585,
        393.88135525, 393.88135525,  98.47033881, 443.11652466,
        246.17584703,  98.47033881, 147.70550822, 196.94067763,
         98.47033881, 443.11652466, 344.64618585, 393.88135525,
         98.47033881, 443.11652466, 196.94067763,  49.23516941,
         98.47033881, 246.17584703, 443.11652466, 147.70550822,
         49.23516941, 196.94067763, 295.41101644]])

In [176]:
print("Максимум= " + str(olap[0,:,:].max()))
print("Минимум= " + str(olap[0,:,:].min()))
print("Среднее= " + str(olap[0,:,:].mean()))

Максимум= 516.9552871330447
Минимум= 32.153281346714984
Среднее= 217.61745856112796

**Максимумы продаж по дням 0-товара для всех магазаинов**

In [177]:
print("Максимумы = " + str(olap[0,:,:].max(axis = 1)))

Максимумы = [294.24670742 289.37953212 516.95528713 502.04219422 392.02013653
 392.82086819 427.17017852 423.36158546 324.6959173  443.11652466]

**Среднемесячные продажи 10-товара для всех магазаинов**

In [178]:
print("Среднее = " + str(olap[10,:,:].mean(axis = 1)))

Среднее = [305.07178682 182.61370176 153.42506435 189.63711223 282.45803911
 222.88413106 160.53342542 234.52207549 163.4703015  324.2560276 ]

**Cумма, максимум, минимум и среднее по продажам 10-20 чисел месяца для товаров [1,3,4] по всем магазинам**

In [179]:
print("Сумма= " + str(olap[[1,3,4],:,10:21].sum()))
print("Максимум= " + str(olap[[1,3,4],:,10:21].max()))
print("Минимум= " + str(olap[[1,3,4],:,10:21].min()))
print("Среднее= " + str(olap[[1,3,4],:,10:21].mean()))

Сумма= 107812.49406513816
Максимум= 1616.5667589059512
Минимум= 19.053951004076684
Среднее= 326.70452747011564

**Cумма, максимум, минимум и среднее по продажам 0-15 чисел месяца для товаров 26-53 по магазинам 2-7**

In [180]:
print("Сумма= " + str(olap[26:54,2:8,:16].sum()))
print("Максимум= " + str(olap[26:54,2:8,:16].max()))
print("Минимум= " + str(olap[26:54,2:8,:16].min()))
print("Среднее= " + str(olap[26:54,2:8,:16].mean()))

Сумма= 1069265.4937293502
Максимум= 1770.7170523871343
Минимум= 6.876431432479832
Среднее= 397.7922223695499

**Сумма продаж для всех товаров в день для каждого магазина**

In [152]:
np.sum(olap, axis = 0)

array([[42745.00723478, 42688.39902274, 41610.85102552, 44482.61805958,
        44620.70057191, 42355.61197492, 42821.50063588, 37445.15365544,
        42752.64911509, 45436.84887035, 37870.13375099, 42547.53691754,
        45833.78673053, 40773.19516476, 40738.43889132, 40302.08256239,
        44790.95186034, 40506.93309252, 39970.58994492, 41614.02288586,
        36647.6568576 , 38842.3865137 , 38670.31261337, 33778.31258272,
        40552.19305714, 42193.33177074, 42434.9370546 , 43032.39126504,
        40714.90269921, 41161.23944565, 37140.7329824 ],
       [41073.42113869, 41425.83839509, 39484.54086586, 40046.7989963 ,
        38870.51234055, 40601.07471656, 41832.47634238, 39267.9617385 ,
        36844.05374288, 39349.71554886, 40333.29636599, 43226.34075402,
        41519.50618864, 39408.86246189, 39861.08468652, 38593.44464983,
        38168.14521951, 41860.47510861, 38196.17151369, 42085.81284888,
        43171.40559683, 41659.61590088, 43867.0483954 , 39276.88396202,
        42458.55158071, 38794.26088796, 39883.69259867, 35525.84458953,
        39731.19406335, 39622.68679105, 41389.31311848],
       [44358.83753959, 40541.32009816, 40415.72109426, 37750.47575477,
        41584.80951918, 40533.38003032, 38695.42225011, 38317.54217663,
        35254.66070572, 42550.14066412, 37109.05680385, 39593.5318007 ,
        39938.24482189, 39847.18310538, 41309.63479635, 42361.66021738,
        36354.62276867, 38623.3590652 , 42338.34952988, 38570.06112592,
        39046.39143754, 36712.24731781, 41706.87445068, 40670.83127679,
        32482.47247309, 39792.15632575, 39749.40568282, 39168.76735282,
        34360.07587766, 40061.09242307, 33360.41227509],
       [41081.07068024, 41468.55620768, 37102.68743215, 41264.5271761 ,
        38077.27413421, 37102.92012981, 36090.7756606 , 36149.59091466,
        35643.15001331, 36796.65756748, 43453.01743975, 36308.10481657,
        33576.48773497, 41106.31565696, 36124.79033038, 34242.76762301,
        36164.72432691, 37944.32747903, 35452.3461927 , 38475.87656361,
        39957.42291327, 37049.11929504, 38212.64236151, 37650.63578404,
        40589.16043713, 44855.82828839, 41151.30741307, 35969.36372845,
        44064.06411444, 39915.11382371, 38792.92459003],
       [36940.79780855, 42511.04218525, 39102.74873433, 42838.11259336,
        41515.77358915, 39178.49165328, 45217.9176025 , 44531.27829021,
        40586.52346541, 40090.67924027, 39505.90111373, 39451.04318936,
        38755.06374014, 41006.49041072, 41534.73640387, 41982.17213222,
        43521.98040989, 41783.8385862 , 41247.12039995, 36200.38536961,
        43712.2097816 , 40337.98804418, 39139.72068417, 36093.80937555,
        43436.58132923, 39775.18478509, 42570.38609487, 41009.62128178,
        43290.62035504, 43330.30155984, 40637.1513796 ],
       [46597.9337485 , 39696.40295381, 41220.44463047, 40728.61681397,
        40281.84964058, 42673.73199567, 46788.47226913, 42324.40302949,
        39289.76274534, 44927.90143137, 40304.3183125 , 42850.98416076,
        38211.34009162, 43683.67301625, 36372.41916226, 41363.02470143,
        38614.58574788, 40680.66793216, 42678.82472497, 45354.20090767,
        40683.45374608, 37711.35266631, 41564.22470592, 40659.51365108,
        40551.14152959, 41534.6592845 , 38818.66569796, 43605.84786458,
        38711.12631424, 40930.82631802, 46278.66104272],
       [40495.14308798, 40590.82977206, 36996.29481717, 37840.94386852,
        38109.23836868, 34194.62244701, 40794.18732504, 39196.99460012,
        37266.03664647, 38458.16223719, 40293.68853744, 44506.09095678,
        40793.93367507, 38254.78427373, 37442.12050066, 44787.82146275,
        38052.86634303, 40109.66272647, 38368.93070769, 38237.05156465,
        44326.82756947, 38501.36800116, 39341.50413421, 42693.64617423,
        40989.46583124, 36934.00592317, 34739.26410616, 42108.63312539,
        40017.22147238, 39779.71020727, 39899.53017927],
       [43445.07348695, 41875.54003387, 41611.25532946, 44718.1954355 ,
        41123.14861243, 42852.37038481, 41759.84342425, 41300.71511112,
        39185.73745755, 44548.55430213, 43395.23825115, 38994.40260852,
        45827.37105814, 38897.64363774, 39931.08284778, 41374.44169501,
        45989.76167496, 39003.65747328, 38393.29674314, 38561.59186742,
        42092.05785484, 42451.19196403, 41480.81604431, 39737.99205673,
        39053.49296504, 41662.34337615, 45088.93959909, 39832.99564848,
        38495.22666309, 43121.08039486, 36191.16286994],
       [39333.8405374 , 39637.00017654, 40142.96607723, 35369.34157341,
        36631.73106187, 39236.21250447, 41777.63027124, 44764.37462224,
        41105.52997249, 36902.65419064, 42474.47579575, 39762.9085564 ,
        43597.71754687, 38314.00453088, 40419.39435003, 41033.44090037,
        43846.57290882, 40911.72084659, 40200.36274382, 39717.96539509,
        39406.50048557, 44904.46336554, 38220.04977527, 45364.38041318,
        40945.1419441 , 47299.86511501, 42500.33012305, 42566.17168605,
        41930.44873308, 43622.13447459, 36355.23927831],
       [41579.04216725, 43673.25689068, 41484.00507164, 40016.68143136,
        42895.94341317, 44227.69352367, 38657.79286002, 31005.23310646,
        37138.92014823, 44747.17621977, 40472.60931179, 39831.88740284,
        40378.04605971, 43568.76794259, 36124.97781883, 42584.86528853,
        41609.10260775, 40344.94497052, 37729.23573899, 36799.33278968,
        45534.84098054, 43418.26602733, 43013.05064929, 44884.68784051,
        41342.56984136, 38964.99021568, 42019.77256607, 43432.40294284,
        36906.03921027, 44267.39779301, 38872.2980596 ]])